DROP TABLE IF EXISTS monthlydata;

CREATE TABLE monthlydata (
id INTEGER PRIMARY KEY AUTOINCREMENT,
title TEXT NOT NULL,
amount FLOAT NOT NULL,
duedate TIMESTAMP NOT NULL,
subtracted BOOL  NOT NULL
);

DROP TABLE IF EXISTS spendings;

CREATE TABLE spendings (
id INTEGER PRIMARY KEY AUTOINCREMENT,
date TIMESTAMP NOT NULL,
amount FLOAT NOT NULL,
subtracted BOOL  NOT NULL
);

