DROP TABLE IF EXISTS monthlydata;

CREATE TABLE monthlydata (
id INTEGER PRIMARY KEY AUTOINCREMENT,
title TEXT NOT NULL,
amount FLOAT NOT NULL,
duedate TIMESTAMP NOT NULL,
subtracted BOOL  NOT NULL
);

DROP TABLE IF EXISTS report;

CREATE TABLE report (
id INTEGER PRIMARY KEY AUTOINCREMENT,
date TIMESTAMP NOT NULL,
title TEXT NOT NULL,
amount FLOAT NOT NULL,
subtracted BOOL  NOT NULL
);

